enum TeacherActionTypes {

	SIGNUP = "TEACHER_SIGNUP",
	SIGNUP_SUCCEED = "TEACHER_SIGNUP_SUCCEED",
	SIGNUP_FAILURE = "TEACHER_SIGNUP_FAILURE",

	LOGIN = "TEACHER_LOGIN",
	LOGIN_SUCCEED = "TEACHER_LOGIN_SUCCEED",
	LOGIN_FAILURE = "TEACHER_LOGIN_FAILURE"
}

export {
	TeacherActionTypes
}