steps:
  - name: "gcr.io/cloud-builders/curl"
    args:
      - "-X"
      - "POST"
      - "--data-urlencode"
      - 'payload={"channel": "#platform-dev", "username": "deploybot", "text": "Starting build of $SHORT_SHA to supplier:$BRANCH_NAME...", "icon_emoji": ":construction_worker:"}'
      - "$_SLACK_URL"
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "asia.gcr.io/$PROJECT_ID/platform-web:$BRANCH_NAME"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "asia.gcr.io/$PROJECT_ID/platform-web:$BRANCH_NAME"
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/platform-web:$SHORT_SHA"
      - "-t"
      - "asia.gcr.io/$PROJECT_ID/platform-web:$BRANCH_NAME"
      - "--build-arg"
      - "VERSION=$SHORT_SHA"
      - "web"
    env:
      - "VERSION=$SHORT_SHA"
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/platform-web:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/$PROJECT_ID/platform-web:$BRANCH_NAME"]
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/platform-web-$BRANCH_NAME",
        "platform-web=asia.gcr.io/$PROJECT_ID/platform-web:$SHORT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=platform-backend-cluster"
  - name: "gcr.io/cloud-builders/curl"
    args:
      - "-X"
      - "POST"
      - "--data-urlencode"
      - 'payload={"channel": "#platform-dev", "username": "deploybot", "text": "Succesfully deployed version $SHORT_SHA of supplier:$BRANCH_NAME", "icon_emoji": ":construction_worker:"}'
      - "$_SLACK_URL"
